on:
  push:
    tags:
      - '/\d+.\d+.\d+/'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts'
      - run: npm ci
      - run: npm run lint
